# fly.toml app configuration file generated for contacts-backend-api-unique on 2024-05-22T20:13:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'contacts-backend-api-unique'
primary_region = 'gig'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  SECRET_KEY = 'your-secret-key'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
